# Project 3: Global Missing Migrants Dataset
Introduction: The Missing Migrants Project, initiated by the International Organization for Migration, documents migrants who have gone missing or have died in their migration to an another location. This project analyzes the data by region, incidents, migration route, and the time period from 2014-2023.

In [49]:
import pandas as pd
df = pd.read_csv("Global Missing Migrants Dataset.csv")
df.head(5)

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
0,Incident,2014,January,Central America,North America,Guatemala,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.650259, -110.366453",Northern America
1,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.59713, -111.73756",Northern America
2,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.94026, -113.01125",Northern America
3,Incident,2014,January,Central America,North America,Mexico,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,"near Douglas, Arizona, USA","Ministry of Foreign Affairs Mexico, Pima Count...","31.506777, -109.315632",Northern America
4,Incident,2014,January,Northern Africa,Europe,Sudan,1.0,0,1,2,0,1,0,Harsh environmental conditions / lack of adequ...,NaN,Border between Russia and Estonia,EUBusiness (Agence France-Presse),"59.1551, 28",Northern Europe

## Data Overview: 
A comprehensive record of missing migrants from the Missing Migrants project which was initiated by International Organization of Migration (IOM). This spans recorded missing migrants from 2014 to 2023.

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13020 entries, 0 to 13019
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Incident Type                        13020 non-null  object
 1   Incident year                        13020 non-null  int64
 2   Reported Month                       13020 non-null  object
 3   Region of Origin                     12998 non-null  object
 4   Region of Incident                   13020 non-null  object
 5   Country of Origin                    13012 non-null  object
 6   Number of Dead                       12470 non-null  float64
 7   Minimum Estimated Number of Missing  13020 non-null  int64
 8   Total Number of Dead and Missing     13020 non-null  int64
 9   Number of Survivors                  13020 non-null  int64
 10  Number of Females                    13020 non-null  int64
 11  Number of Males                      13020 non-null  int64
 12  Number of Children                   13020 non-null  int64
 13  Cause of Death                       13020 non-null  object
 14  Migration route                      9999 non-null   object
 15  Location of death                    13020 non-null  object
 16  Information Source                   13012 non-null  object
 17  Coordinates                          12984 non-null  object
 18  UNSD Geographical Grouping           13019 non-null  object
dtypes: float64(1), int64(7), object(11)
memory usage: 1.9+ MB

In [51]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [52]:
df.describe()

,incident_year,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children
count,13020.000000,12470.000000,13020.000000,13020.000000,13020.000000,13020.000000,13020.000000,13020.000000
mean,2019.060753,2.623737,1.904378,4.417281,6.553763,0.458372,1.116052,0.238095
std,2.418738,9.728163,15.645297,19.950630,42.315444,2.853658,3.811134,2.417196
min,2014.000000,0.000000,-2.000000,1.000000,-2.000000,0.000000,0.000000,0.000000
25%,2017.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,2019.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,2021.000000,2.000000,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000
max,2023.000000,750.000000,750.000000,1022.000000,1950.000000,94.000000,135.000000,250.000000

In [53]:
df.isnull().sum()

incident_type                             0
incident_year                             0
reported_month                            0
region_of_origin                         22
region_of_incident                        0
country_of_origin                         8
number_of_dead                          550
minimum_estimated_number_of_missing       0
total_number_of_dead_and_missing          0
number_of_survivors                       0
number_of_females                         0
number_of_males                           0
number_of_children                        0
cause_of_death                            0
migration_route                        3021
location_of_death                         0
information_source                        8
coordinates                              36
unsd_geographical_grouping                1
dtype: int64

## Data Cleaning:
* Investigated region labels containing "(P)" and retained them in the dataset, as they appear to indicate presumed region/country of origin when exact origin information was uncertain.
* Standardized entries within the Information Source column to correct spelling inconsistencies and merge duplicate categories.
* Investigated 654 duplicate records and retained them because they appeared to represent separate observations rather than obvious data-entry errors.
* Replaced missing values in categorical variables such as Region of Origin, Country of Origin, Migration Route, Information Source, and UNSD Geographical Grouping with "Unknown" where appropriate.
* Retained missing values (NaN) in numerical and geographic fields where information was unavailable, including Number of Dead and Coordinates.

In [54]:
df['region_of_origin'].value_counts()

region_of_origin
Latin America / Caribbean (P)    2164
Southern Asia                    1904
Unknown                          1737
Central America                  1565
Sub-Saharan Africa (P)           1528
Eastern Africa (P)               1133
Northern Africa                   452
Western Asia                      432
South America                     322
Eastern Africa                    298
Caribbean                         278
Western / Southern Asia (P)       245
Western Africa                    229
Northern Africa (P)               122
Sub-Saharan Africa                116
Mixed                             111
Southern Asia (P)                  90
South-eastern Asia                 68
Western Africa (P)                 52
Middle Africa                      51
South America (P)                  18
Europe                             14
Western / Southern Asia            14
Western Asia (P)                   12
Eastern Asia                       11
Caribbean (P)                      10
Central America (P)                 8
Southern Africa                     5
Central Asia                        4
Northern America                    2
Eastern Asia (P)                    1
South-eastern Asia (P)              1
Oceania                             1
Name: count, dtype: int64

In [55]:
df[df['region_of_origin'].isnull()]

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
1217,Incident,2016,January,NaN,Mediterranean,"Afghanistan,Iraq,Syrian Arab Republic",39.0,0,39,75,0,0,5,Drowning,Eastern Mediterranean,"between Ayvacik, Canakkale, Türkiye and Lesvos...",Turkish Coast Guard via IOM Athens. AFP and th...,"39.2893824, 26.4734281",Uncategorized
12923,Incident,2023,January,NaN,Northern Africa,Sudan,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.22092653, 23.291791",Northern Africa
12924,Incident,2023,January,NaN,Northern Africa,Egypt,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Qondofah, Benghazi, Libya",IOM Libya Displacement Tracking Matrix,"32.029039, 20.016156",Northern Africa
12925,Incident,2023,January,NaN,Northern Africa,Unknown,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Al-Madina, Tobruk, Libya",IOM Libya Displacement Tracking Matrix,"32.09704552, 23.991754",Northern Africa
12926,Incident,2023,February,NaN,Northern Africa,Nigeria,1.0,0,1,0,0,1,0,Vehicle accident / death linked to hazardous t...,NaN,"Rass Al-Magil, Misrata, Libya",IOM Libya Displacement Tracking Matrix,"32.33801861, 15.044267",Northern Africa
12927,Incident,2023,February,NaN,Northern Africa,Sudan,1.0,0,1,0,0,1,0,Accidental death,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20637163, 23.290346",Northern Africa
12928,Incident,2023,January,NaN,Northern Africa,Unknown,3.0,0,3,4,0,7,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"31.04216493, 14.431426",Northern Africa
12929,Incident,2023,February,NaN,Northern Africa,Unknown,3.0,0,3,0,1,2,0,Mixed or unknown,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12930,Incident,2023,February,NaN,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Harsh environmental conditions / lack of adequ...,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12931,Incident,2023,March,NaN,Northern Africa,Chad,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Gatroun, Al-Qatroun, Libya",IOM Libya Displacement Tracking Matrix,"24.94447643, 14.627779",Northern Africa
12932,Incident,2023,March,NaN,Northern Africa,Syrian Arab Republic,1.0,0,1,1,0,2,0,Harsh environmental conditions / lack of adequ...,Sahara Desert crossing,"Umm Sa'ad, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12933,Incident,2023,March,NaN,Northern Africa,Unknown,2.0,6,8,8,0,8,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bazimah in the Soutth of Rbaaniah, Al-Kufra, L...",IOM Libya Displacement Tracking Matrix,"21.95627, 24.25597",Northern Africa
12934,Incident,2023,March,NaN,Northern Africa,Unknown,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Qatrun, Al-gatroun, Libya",IOM Libya Displacement Tracking Matrix,"27.04400604, 14.436574",Northern Africa
12935,Incident,2023,March,NaN,Northern Africa,Mauritania,2.0,0,2,3,0,2,1,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Qatrun, Al-gatroun, Libya",IOM Libya Displacement Tracking Matrix,"27.04400604, 14.436574",Northern Africa
12936,Incident,2023,April,NaN,Northern Africa,Unknown,6.0,0,6,2,0,8,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bint Bayya, Wadi al Shatii District, Libya",IOM Libya Displacement Tracking Matrix,"27.48775812, 13.360607",Northern Africa
12937,Incident,2023,April,NaN,Northern Africa,Nigeria,2.0,0,2,0,0,2,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"14.22490057, 65.555267",Northern Africa
12938,Incident,2023,April,NaN,Northern Africa,Unknown,8.0,0,8,18,0,8,0,Mixed or unknown,Sahara Desert crossing,"Brak, Libya",IOM Libya Displacement Tracking Matrix,"27.54179645, 14.300551",Northern Africa
12939,Incident,2023,April,NaN,Northern Africa,Egypt,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Umm Sa'ad, Libya",IOM Libya Displacement Tracking Matrix,"31.6488315, 25.052252",Northern Africa
12940,Incident,2023,May,NaN,Northern Africa,Unknown,5.0,0,5,8,0,0,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bouzreq, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.92367718, 22.107087",Northern Africa
12941,Incident,2023,May,NaN,Northern Africa,Bangladesh,8.0,0,8,0,0,8,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Qaminis, Libya",IOM Libya Displacement Tracking Matrix,"31.65071241, 20.011192",Northern Africa
12942,Incident,2023,May,NaN,Northern Africa,Unknown,1.0,0,1,0,0,1,0,Accidental death,Sahara Desert crossing,"Umm Sa'ad, Libya",IOM Libya Displacement Tracking Matrix,"31.6124278, 25.046548",Northern Africa
12943,Incident,2023,May,NaN,Northern Africa,Unknown,1.0,0,1,6,0,7,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"14.22490057, 65.555267",Northern Africa

In [56]:
df['region_of_origin'].value_counts()

region_of_origin
Latin America / Caribbean (P)    2164
Southern Asia                    1904
Unknown                          1737
Central America                  1565
Sub-Saharan Africa (P)           1528
Eastern Africa (P)               1133
Northern Africa                   452
Western Asia                      432
South America                     322
Eastern Africa                    298
Caribbean                         278
Western / Southern Asia (P)       245
Western Africa                    229
Northern Africa (P)               122
Sub-Saharan Africa                116
Mixed                             111
Southern Asia (P)                  90
South-eastern Asia                 68
Western Africa (P)                 52
Middle Africa                      51
South America (P)                  18
Europe                             14
Western / Southern Asia            14
Western Asia (P)                   12
Eastern Asia                       11
Caribbean (P)                      10
Central America (P)                 8
Southern Africa                     5
Central Asia                        4
Northern America                    2
Eastern Asia (P)                    1
South-eastern Asia (P)              1
Oceania                             1
Name: count, dtype: int64

In [57]:
df['region_of_origin'] = df['region_of_origin'].fillna('Unknown')

In [58]:
df[df['country_of_origin'].isnull()].head(10)

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
132,Incident,2014,July,Unknown,Mediterranean,NaN,13.0,0,13,0,0,0,0,Mixed or unknown,Central Mediterranean,Boat drifting in Libyan waters,IANS,"33.0335, 15",Uncategorized
185,Incident,2014,August,Unknown,Mediterranean,NaN,0.0,100,100,0,0,0,0,Drowning,Central Mediterranean,"Off the shore of al-Qarbouli, Libya",Press Association,"32.8879, 14",Uncategorized
254,Cumulative Incident,2014,September,Unknown,Eastern Africa,NaN,16.0,0,16,0,0,0,0,Mixed or unknown,Horn of Africa to Yemen crossing,Multiple locations,IOM Djibouti,"9.1303782, 41.2808577",Uncategorized
423,Incident,2015,May,South-eastern Asia,South-eastern Asia,NaN,2.0,0,2,0,0,0,0,Mixed or unknown,NaN,"Trafficking camps in Phang Nga province, Thailand",The Guardian,"8.4501414, 98.525532",South-eastern Asia
761,Incident,2015,October,Latin America / Caribbean (P),Central America,NaN,1.0,0,1,0,0,1,0,Violence,NaN,"Xaloztoc, Tlaxcala, Mexico",Agenda Tlaxcala,"19.408, -98.052",Central America
922,Incident,2015,November,Central America,North America,NaN,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.511, -111.561833",Northern America
974,Incident,2015,December,Central America,North America,NaN,1.0,0,1,0,0,1,0,Drowning,US-Mexico border crossing,"All American Canal, CA near Calexico",El Mexicano,"32.668019, -115.502043",Northern America
1003,Incident,2015,December,Eastern Africa (P),Northern Africa,NaN,2.0,0,2,0,0,0,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Sabha, Libya",Mixed Migration Monitoring Mechanism Initative...,"27.032288, 14.456116",Northern Africa

In [59]:
df['country_of_origin'] = df['country_of_origin'].fillna('Unknown')

In [60]:
df['country_of_origin'].value_counts().tail(55)

country_of_origin
Egypt,Eritrea,Sudan,Syrian Arab Republic                           1
Libya,Morocco,Syrian Arab Republic                                 1
Ecuador,Guatemala                                                  1
Myanmar,Viet Nam                                                   1
Angola,Cuba                                                        1
Côte d'Ivoire,Mali,Senegal,Unknown                                 1
Bangladesh,Egypt,Morocco,Unknown                                   1
Guinea,Senegal                                                     1
Somalia,State of Palestine,Syrian Arab Republic,Yemen              1
India,Pakistan                                                     1
Kenya                                                              1
Eritrea,Sudan                                                      1
Lao People's Democratic Republic                                   1
Egypt,Pakistan                                                     1
Morocco,Somalia,Unknown                                            1
Bangladesh,Mixed                                                   1
Georgia                                                            1
Belize                                                             1
Algeria,Eritrea,Libya,Morocco,Nigeria,Unknown                      1
Afghanistan,Iraq,Somalia,Syrian Arab Republic,Unknown              1
Afghanistan,Pakistan,Syrian Arab Republic                          1
Algeria,Tunisia,Unknown                                            1
South Sudan                                                        1
Chad,Egypt,Nigeria,Sudan                                           1
Oman                                                               1
Guinea,Mexico,Sudan                                                1
Bangladesh,Pakistan                                                1
Unknown,Yemen                                                      1
Cameroon,Guinea,Unknown                                            1
Nigeria,Senegal                                                    1
Bahamas                                                            1
Guinea,Mali,Senegal                                                1
Brazil,Cuba,Dominican Republic                                     1
Cameroon,Côte d'Ivoire,Senegal                                     1
Congo,Morocco,Unknown                                              1
Mali,Senegal                                                       1
Gambia,Unknown                                                     1
Ghana,Guinea,Senegal                                               1
Cameroon,Congo,Syrian Arab Republic,Türkiye                        1
Bangladesh,Senegal,Unknown                                         1
Ecuador,Guatemala,Mexico,Unknown                                   1
Burkina Faso,Côte d'Ivoire,Gambia,Nigeria                          1
Congo,Guinea                                                       1
Angola,Congo                                                       1
Burkina Faso                                                       1
Türkiye,Unknown                                                    1
Cameroon,Côte d'Ivoire,Guinea,Mali,Nigeria,Sierra Leone            1
El Salvador,Honduras,Unknown                                       1
Libya,Pakistan,Unknown                                             1
Côte d'Ivoire,Tunisia,Unknown                                      1
Nigeria,Sudan                                                      1
Mali,Senegal,Unknown                                               1
Somalia,Unknown                                                    1
Cameroon,Côte d'Ivoire,Democratic Republic of the Congo,Tunisia    1
Gambia,Mali,Nigeria,Senegal,Unknown                                1
Name: count, dtype: int64

In [61]:
df[df['number_of_dead'].isnull()]

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
295,Split Incident,2014,October,Western Asia,Mediterranean,"State of Palestine,Sudan",NaN,6,6,20,0,3,0,Drowning,Eastern Mediterranean,<p>Unspecified location in the Aegean Sea betw...,rd.nl,"38.74477, 26.486067",Uncategorized
336,Incident,2015,February,Western Africa,Mediterranean,"Côte d'Ivoire,Gambia,Guinea,Mali,Mauritania,Ni...",NaN,307,307,9,0,0,0,Drowning,Central Mediterranean,Between Libya and Lampedusa,IOM Italy from Flavio 29/04/2015,"34.3616, 12.9858",Uncategorized
351,Incident,2015,March,Sub-Saharan Africa (P),Western Africa,Unknown,NaN,25,25,0,0,0,0,Drowning,Western Africa / Atlantic route to the Canary ...,"Off the coast of Nuadibu, Mauritania",Asociación Pro Derechos Humanos de Andalucía,"20.94764809, -17.087039",Uncategorized
378,Cumulative Incident,2015,March,South-eastern Asia,South-eastern Asia,Myanmar,NaN,243,243,0,0,0,0,Mixed or unknown,NaN,Bay of Bengal,UNHCR,"17.64473, 92.46209",South-eastern Asia
379,Cumulative Incident,2015,March,South-eastern Asia,South-eastern Asia,Myanmar,NaN,130,130,0,0,0,0,Drowning,NaN,"Bay of Bengal - departed from Myanmar, Rakhine...",Arakan Project,"13.498141, 89.487406",South-eastern Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12946,Incident,2023,July,Unknown,Northern Africa,Unknown,NaN,1,1,21,0,0,0,Mixed or unknown,NaN,"Survivors rescued from Tawil Rutba, near Al-As...",IOM Libya,"32.80827441, 11.584487",Northern Africa
12950,Incident,2023,July,Unknown,Northern Africa,Unknown,NaN,2,2,12,0,0,0,Mixed or unknown,NaN,"Survivors rescued from Tawil Rutba, near Al-As...",IOM Libya,"32.80827441, 11.584487",Northern Africa
12966,Incident,2023,July,Unknown,Mediterranean,Unknown,NaN,4,4,13,0,0,0,Drowning,Western Mediterranean,"Unspecified location ""far"" from the coast of A...",Heroes del Mar,"36.3423573, -1.783771",Uncategorized
12967,Split Incident,2023,July,Western Asia,Mediterranean,"Algeria,Syrian Arab Republic",NaN,10,10,1,1,7,2,Drowning,Western Mediterranean,Unspecified location in international waters a...,Heroes del Mar,"36.09861941, -1.432208",Uncategorized
13011,Incident,2023,July,Central America,North America,Mexico,NaN,1,1,0,0,1,0,Mixed or unknown,NaN,"Fruit Stand & Orchards, Osooyos, British Colum...","Gendarmerie royale du Canada, El Mañana","49.02831207, -119.432156",Northern Africa

In [62]:
df['number_of_dead'] = df['number_of_dead'].fillna('NaN')

In [63]:
df[df['migration_route'].isnull()]

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
4,Incident,2014,January,Northern Africa,Europe,Sudan,1.0,0,1,2,0,1,0,Harsh environmental conditions / lack of adequ...,NaN,Border between Russia and Estonia,EUBusiness (Agence France-Presse),"59.1551, 28",Northern Europe
16,Cumulative Incident,2014,February,South-eastern Asia,South-eastern Asia,Myanmar,5.0,0,5,500,0,5,0,Sickness / lack of access to adequate healthcare,NaN,"Hat Yai hospital, 182 Ratthakan, Hat Yai, Hat ...",Manager Online,"7.0167471, 100.4674982",South-eastern Asia
28,Incident,2014,February,Southern Asia,Southern Asia,Bangladesh,1.0,0,1,0,0,1,0,Violence,NaN,India,Daily Star,"25.1841, 89",Southern Asia
33,Incident,2014,March,Southern Asia,South-eastern Asia,Cambodia,5.0,0,5,4,2,3,0,Vehicle accident / death linked to hazardous t...,NaN,"Bypass Road, Moo 7, Bang Phra subdistrict, Sri...","Manager Online, INN News, Khomchudluek","13.2353642, 101",South-eastern Asia
34,Incident,2014,March,Southern Asia,South-eastern Asia,Myanmar,2.0,0,2,10,0,2,0,Vehicle accident / death linked to hazardous t...,NaN,"Moo 13, 38th km of the 4006 Langsuan-Pato Road...","INN News, Manager Online, Daily News","9.96833, 99",South-eastern Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13004,Incident,2023,July,Unknown,Northern Africa,Unknown,1.0,0,1,0,1,0,0,Mixed or unknown,NaN,"Body recovered near Tawil Rutba, Libya, presum...",IOM Libya,"32.80827441, 11.584487",Northern Africa
13005,Incident,2023,July,Western Africa,Northern Africa,Sierra Leone,1.0,0,1,0,1,0,0,Mixed or unknown,NaN,"Body recovered near Tawil Rutba, Libya, presum...",IOM Libya,"32.80827441, 11.584487",Northern Africa
13006,Incident,2023,July,Unknown,Northern Africa,Unknown,1.0,0,1,10,0,1,0,Mixed or unknown,NaN,"Body recovered near Tawil Rutba, Libya, presum...",IOM Libya,"32.80827441, 11.584487",Northern Africa
13011,Incident,2023,July,Central America,North America,Mexico,NaN,1,1,0,0,1,0,Mixed or unknown,NaN,"Fruit Stand & Orchards, Osooyos, British Colum...","Gendarmerie royale du Canada, El Mañana","49.02831207, -119.432156",Northern Africa
13012,Incident,2023,July,Central America,Central America,Honduras,1.0,0,1,0,0,1,0,Harsh environmental conditions / lack of adequ...,NaN,"Near San Rafael housing unit, San Francisco Co...",El Sol de Toluca,"19.64315027, -99.084743",Central America

In [64]:
df['migration_route'].value_counts()

migration_route
US-Mexico border crossing                                3392
Sahara Desert crossing                                   2046
Central Mediterranean                                    1106
Afghanistan to Iran                                      1099
Western Mediterranean                                     614
Eastern Mediterranean                                     336
Western Africa / Atlantic route to the Canary Islands     226
Western Balkans                                           210
Horn of Africa to Yemen crossing                          161
Türkiye-Europe land route                                 157
English Channel to the UK                                 134
Syria to Türkiye                                          129
Darien                                                     98
Caribbean to US                                            63
Belarus-EU border                                          61
Dominican Republic to Puerto Rico                          42
Iran to Türkiye                                            34
Italy to France                                            33
Haiti to Dominican Republic                                17
Comoros to Mayotte                                         16
Venezuela to Caribbean                                     11
Ukraine to Europe                                           9
DRC to Uganda                                               3
Central Mediterranean,Sahara Desert crossing                1
Caribbean to Central America                                1
Name: count, dtype: int64

In [65]:
df['migration_route'] = df['migration_route'].fillna('Unknown')

In [66]:
df[df['information_source'].isnull()]

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
62,Incident,2014,April,Western Asia,Mediterranean,Syrian Arab Republic,8.0,1,9,5,2,0,1,Drowning,Eastern Mediterranean,Türkiye waters - en route to Greece,NaN,"38.669208, 27",Uncategorized
465,Incident,2015,June,Latin America / Caribbean (P),Central America,Unknown,3.0,0,3,117,0,0,0,Violence,Unknown,"Sonora, Mexico",NaN,"29.3766625, -113.982346",Central America
545,Incident,2015,July,Latin America / Caribbean (P),North America,Unknown,2.0,0,2,0,0,0,0,Mixed or unknown,US-Mexico border crossing,"Desert near Carrizo Springs, Dimmit County, Te...",NaN,"28.2597513, -100.245529",Northern America
724,Incident,2015,September,Central America,Central America,"Guatemala,Honduras",2.0,0,2,0,0,0,0,Vehicle accident / death linked to hazardous t...,Unknown,"Puebla, Mexico",NaN,"19.049997, -98.199999",Central America
3142,Incident,2017,August,Unknown,South-eastern Asia,Unknown,2.0,0,2,0,0,2,0,Harsh environmental conditions / lack of adequ...,Unknown,"Kuala Lumpur, Malaysia",NaN,"3.233046, 101.610573",South-eastern Asia
5360,Incident,2018,February,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,NaN,"33.061615, -113.367348",NaN
6987,Incident,2019,November,Eastern Africa,Western Asia,Ethiopia,26.0,0,26,74,8,18,0,Violence,Unknown,"Near Al-Raqw Market, Monabbih, Saada province,...",NaN,"17.245130865, 43.239432135",Western Asia
8176,Incident,2020,December,Northern Africa (P),Mediterranean,Unknown,NaN,5,5,0,0,5,0,Drowning,Western Mediterranean,Unspecified location in the Alboran Sea. Depar...,NaN,"35.30420753, -3.92007383",Uncategorized

In [67]:
df['information_source'] = df['information_source'].fillna('Unknown')

In [68]:
df['information_source'].value_counts().head(55)

information_source
IOM Afghanistan                                          1538
Pima County Office of the Medical Examiner (PCOME)       1480
Mixed Migration Monitoring Mechanism Initiative (4Mi)    1089
Mixed Migration Monitoring Mechanism Initative (4mi)      992
Mixed Migration Monitoring Mechanism Initiative (4mi)     673
IOM Libya                                                 354
MHub                                                      182
US Border Patrol                                          132
Syrian Observatory for Human Rights                        99
Zócalo                                                     96
IOM Italy                                                  74
UNHCR                                                      73
IOM Libya Displacement Tracking Matrix                     71
OHCHR Special Procedures letter                            68
Imperial County Coroner's Office                           62
IOM Djibouti                                               48
South Texas Human Rights Center                            46
Hidalgo County Sheriff's Office                            43
IOM Türkiye                                                37
Imperial County Coroners Office                            37
IOM Greece                                                 37
IOM Somalia                                                36
Imperial County Sheriff's Office                           35
IOM Niger Displacement Tracking Matrix (DTM)               35
Instituto Nacional de Migración México: Grupos Beta        33
Pima County Office of the Medical Examiner                 31
Hoy Tamaulipas                                             30
Survivor testimony via IOM Panama                          30
Caminando Fronteras                                        29
El Mañana                                                  29
CIPIMD                                                     29
Instituto Nacional de Migración (Grupos Beta)              29
Alarm Phone                                                28
Reuters                                                    26
Hurriyet Daily News                                        25
AP                                                         24
IOM Tunisia                                                24
AFP                                                        22
LRC via IOM Libya                                          21
Gendarmerie General Command Türkiye via IOM Türkiye        21
IOM Rome                                                   21
Hellenic Coast Guard                                       20
Zócalo, Super Channel 12                                   20
Brooks County Sheriff's Office via Breitbart News          20
Super Channel 12                                           19
IOM Niger Displacement Tracking Matrix                     19
Asociación Pro Derechos Humanos de Andalucía               19
Hellenic Coast Guard via IOM Greece                        18
IOM Mali Displacement Tracking Matrix                      17
La Rancherita del Aire                                     16
IOM Ethiopia                                               15
Breitbart                                                  14
Terrell County Sheriff's Office                            14
Yuma County Medical Examiner                               14
La Prensa                                                  13
Name: count, dtype: int64

In [69]:
df['information_source'] = df['information_source'].replace({'Mixed Migration Monitoring Mechanism Initative (4mi)':'Mixed Migration Monitoring Mechanism Initiative (4Mi)','Mixed Migration Monitoring Mechanism Initiative (4mi)':'Mixed Migration Monitoring Mechanism Initiative (4Mi)'})

In [70]:
df['information_source'].value_counts().head(55)

information_source
Mixed Migration Monitoring Mechanism Initiative (4Mi)    2754
IOM Afghanistan                                          1538
Pima County Office of the Medical Examiner (PCOME)       1480
IOM Libya                                                 354
MHub                                                      182
US Border Patrol                                          132
Syrian Observatory for Human Rights                        99
Zócalo                                                     96
IOM Italy                                                  74
UNHCR                                                      73
IOM Libya Displacement Tracking Matrix                     71
OHCHR Special Procedures letter                            68
Imperial County Coroner's Office                           62
IOM Djibouti                                               48
South Texas Human Rights Center                            46
Hidalgo County Sheriff's Office                            43
Imperial County Coroners Office                            37
IOM Greece                                                 37
IOM Türkiye                                                37
IOM Somalia                                                36
IOM Niger Displacement Tracking Matrix (DTM)               35
Imperial County Sheriff's Office                           35
Instituto Nacional de Migración México: Grupos Beta        33
Pima County Office of the Medical Examiner                 31
Survivor testimony via IOM Panama                          30
Hoy Tamaulipas                                             30
CIPIMD                                                     29
Instituto Nacional de Migración (Grupos Beta)              29
El Mañana                                                  29
Caminando Fronteras                                        29
Alarm Phone                                                28
Reuters                                                    26
Hurriyet Daily News                                        25
AP                                                         24
IOM Tunisia                                                24
AFP                                                        22
LRC via IOM Libya                                          21
IOM Rome                                                   21
Gendarmerie General Command Türkiye via IOM Türkiye        21
Brooks County Sheriff's Office via Breitbart News          20
Zócalo, Super Channel 12                                   20
Hellenic Coast Guard                                       20
Asociación Pro Derechos Humanos de Andalucía               19
Super Channel 12                                           19
IOM Niger Displacement Tracking Matrix                     19
Hellenic Coast Guard via IOM Greece                        18
IOM Mali Displacement Tracking Matrix                      17
La Rancherita del Aire                                     16
IOM Ethiopia                                               15
Terrell County Sheriff's Office                            14
Yuma County Medical Examiner                               14
Breitbart                                                  14
Hellenic Coast Guard via IOM Athens                        13
La Prensa                                                  13
Action Group for Palestinians of Syria                     13
Name: count, dtype: int64

In [71]:
df[df['coordinates'].isnull()]

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
231,Incident,2014,October,Unknown,Mediterranean,Unknown,0.0,20,20,93,0,0,0,Drowning,Central Mediterranean,off the coast of Libya,Mail Online and IOM Rome,NaN,Uncategorized
256,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
257,Incident,2014,February,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Harsh environmental conditions / lack of adequ...,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
258,Incident,2014,March,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
259,Incident,2014,April,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
260,Incident,2014,April,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
261,Incident,2014,May,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
262,Incident,2014,June,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
263,Incident,2014,June,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
264,Incident,2014,July,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
265,Incident,2014,September,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
267,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
270,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
271,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
272,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
273,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
274,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
275,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
276,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
277,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
278,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
279,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
280,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
281,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
282,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
283,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,1,0,0,Harsh environmental conditions / lack of adequ...,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
284,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
285,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
286,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
287,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
288,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
289,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
290,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
291,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
292,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
293,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America

In [72]:
df['coordinates'] = df['coordinates'].fillna('NaN')

In [73]:
df[df['unsd_geographical_grouping'].isnull()]

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
5360,Incident,2018,February,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Unknown,"33.061615, -113.367348",NaN

In [74]:
df['unsd_geographical_grouping'] = df['unsd_geographical_grouping'].fillna('Unknown')

In [75]:
df['unsd_geographical_grouping'].value_counts()

unsd_geographical_grouping
Northern America      2708
Uncategorized         2351
Northern Africa       1872
Southern Asia         1660
Central America       1362
Western Africa         941
Eastern Africa         467
Western Asia           389
Southern Europe        329
South-eastern Asia     225
South America          207
Western Europe         156
Caribbean              113
Eastern Europe         111
Middle Africa           75
Northern Europe         25
Eastern Asia            15
Southern Africa         12
Central Asia             1
Unknown                  1
Name: count, dtype: int64

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13020 entries, 0 to 13019
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   incident_type                        13020 non-null  object
 1   incident_year                        13020 non-null  int64
 2   reported_month                       13020 non-null  object
 3   region_of_origin                     13020 non-null  object
 4   region_of_incident                   13020 non-null  object
 5   country_of_origin                    13020 non-null  object
 6   number_of_dead                       13020 non-null  object
 7   minimum_estimated_number_of_missing  13020 non-null  int64
 8   total_number_of_dead_and_missing     13020 non-null  int64
 9   number_of_survivors                  13020 non-null  int64
 10  number_of_females                    13020 non-null  int64
 11  number_of_males                      13020 non-null  int64
 12  number_of_children                   13020 non-null  int64
 13  cause_of_death                       13020 non-null  object
 14  migration_route                      13020 non-null  object
 15  location_of_death                    13020 non-null  object
 16  information_source                   13020 non-null  object
 17  coordinates                          13020 non-null  object
 18  unsd_geographical_grouping           13020 non-null  object
dtypes: int64(7), object(12)
memory usage: 1.9+ MB

In [77]:
df.duplicated().sum()

np.int64(641)

In [78]:
df[df.duplicated()].head(45)

,incident_type,incident_year,reported_month,region_of_origin,region_of_incident,country_of_origin,number_of_dead,minimum_estimated_number_of_missing,total_number_of_dead_and_missing,number_of_survivors,number_of_females,number_of_males,number_of_children,cause_of_death,migration_route,location_of_death,information_source,coordinates,unsd_geographical_grouping
222,Incident,2014,October,Eastern Africa,Eastern Africa,Unknown,1.0,0,1,0,0,1,0,Drowning,Horn of Africa to Yemen crossing,Between Bosaso and Yemen (Bin Sinaa),SHS,"12.5331, 48",Uncategorized
223,Incident,2014,October,Eastern Africa,Eastern Africa,Unknown,1.0,0,1,0,0,1,0,Drowning,Horn of Africa to Yemen crossing,Between Bosaso and Yemen (Bin Sinaa),SHS,"12.5331, 48",Uncategorized
224,Incident,2014,October,Eastern Africa,Eastern Africa,Unknown,1.0,0,1,0,0,1,0,Drowning,Horn of Africa to Yemen crossing,Between Bosaso and Yemen (Bin Sinaa),SHS,"12.5331, 48",Uncategorized
263,Incident,2014,June,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
270,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
271,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
272,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
273,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
275,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
276,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
277,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
278,Incident,2014,October,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
280,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
281,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
282,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
284,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
285,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
286,Incident,2014,November,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
288,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
289,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
290,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
291,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
292,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
293,Incident,2014,December,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,NaN,Northern America
460,Incident,2015,May,Unknown,Western Africa,Unknown,1.0,0,1,0,0,0,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Sahara Desert, between Agadez, Niger and Tripo...",MHub,"24.02673196, 13.154261",Western Africa
647,Incident,2015,August,Unknown,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Unspecified location, Libya",MHub,"26.239989, 12.913084",Northern Africa
823,Incident,2015,October,Eastern Africa (P),Northern Africa,Unknown,1.0,0,1,0,0,0,0,Harsh environmental conditions / lack of adequ...,Sahara Desert crossing,"Kufra, Libya",Mixed Migration Monitoring Mechanism Initiativ...,"23.321289, 21.866882",Northern Africa
830,Incident,2015,October,Eastern Africa (P),Northern Africa,Unknown,1.0,0,1,0,0,0,0,Sickness / lack of access to adequate healthcare,Unknown,"Wad Madani, Sudan",Mixed Migration Monitoring Mechanism Initiativ...,"14.393127, 33.539307",Northern Africa
1182,Incident,2016,January,Western Asia,Western Asia,Syrian Arab Republic,1.0,0,1,0,0,1,0,Violence,Syria to Türkiye,Syrian/Turkish border near northern Deir Ezzor...,Syrian Observatory for Human Rights,"36.7188825, 39.4889524",Western Asia
1187,Incident,2016,January,Western / Southern Asia (P),Europe,Unknown,1.0,0,1,0,0,1,0,Harsh environmental conditions / lack of adequ...,Western Balkans,"Western Bulgaria, near Serbian border",UNHCR,"42.8472657, 22.7585621",Eastern Europe
1214,Incident,2016,January,Eastern Africa (P),Northern Africa,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,Sahara Desert crossing,"Aswan, Egypt",Mixed Migration Monitoring Mechanism Initiativ...,"23.285107, 31.5204557",Northern Africa
1223,Incident,2016,January,Unknown,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Violence,Sahara Desert crossing,"Unspecified location, Libya",MHub,"27.0663171, 14.3336145",Northern Africa
1226,Incident,2016,January,Unknown,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Violence,Sahara Desert crossing,"Unspecified location, Libya",MHub,"27.0663171, 14.3336145",Northern Africa
1228,Incident,2016,January,Unknown,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Violence,Sahara Desert crossing,"Unspecified location, Libya",MHub,"27.0663171, 14.3336145",Northern Africa
1271,Incident,2016,February,Eastern Africa (P),Eastern Africa,Unknown,1.0,0,1,0,0,0,0,Sickness / lack of access to adequate healthcare,Unknown,"Las'anod, Somalia",Mixed Migration Monitoring Mechanism Initiativ...,"8.476128, 47.3474798",Eastern Africa
1272,Incident,2016,February,Eastern Africa (P),Eastern Africa,Unknown,1.0,0,1,0,0,0,0,Violence,Unknown,"Gondor, Ethiopia",Mixed Migration Monitoring Mechanism Initiativ...,"12.601127, 37.4389385",Eastern Africa
1274,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,3.0,0,3,0,0,0,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Sabha, Libya",Mixed Migration Monitoring Mechanism Initiativ...,"27.0295078, 14.3890835",Northern Africa
1275,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,2.0,0,2,0,0,0,0,Violence,Sahara Desert crossing,"Qalabat, Sudan",Mixed Migration Monitoring Mechanism Initiativ...,"13.9731737, 35.3431691",Northern Africa
1277,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,3.0,0,3,0,0,0,0,Violence,Sahara Desert crossing,"Qalabat, Sudan",Mixed Migration Monitoring Mechanism Initiativ...,"13.9731737, 35.3431691",Northern Africa
1284,Incident,2016,February,Western Asia,Western Asia,Syrian Arab Republic,1.0,0,1,0,1,0,0,Violence,Syria to Türkiye,"Syrian/Turkish border near Qamishli, Al Hasaka...",Action Group for Palestinians of Syria,"36.5044741, 40.708528",Western Asia
1291,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,6.0,0,6,0,0,0,0,Sickness / lack of access to adequate healthcare,Unknown,"Ajdabiya, Libya",Mixed Migration Monitoring Mechanism Initiativ...,"30.2723743, 19.0741052",Northern Africa
1294,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,1.0,0,1,0,0,0,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Qadarif, Sudan",Mixed Migration Monitoring Mechanism Initiativ...,"14.0316722, 35.3417723",Northern Africa
1297,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,3.0,0,3,0,0,0,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Sabha, Libya",Mixed Migration Monitoring Mechanism Initiativ...,"27.0295078, 14.3890835",Northern Africa
1311,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,3.0,0,3,0,0,0,0,Mixed or unknown,Sahara Desert crossing,"Kurfrah, Libya",Mixed Migration Monitoring Mechanism Initiativ...,"23.2488413, 19.7242161",Northern Africa
1312,Incident,2016,February,Eastern Africa (P),Northern Africa,Unknown,6.0,0,6,0,0,0,0,Mixed or unknown,Sahara Desert crossing,"Kurfrah, Libya",Mixed Migration Monitoring Mechanism Initiativ...,"23.2488413, 19.7242161",Northern Africa

Notes: Duplicates remained as the data sometimes has different coordinates, different numbers of people identified, and sometimes seems to be separate inputs for each individual. Information source for mixed migration monitoring mechanism initiative.

## Exploration Analysis

In [79]:
df['incident_type'].value_counts()

incident_type
Incident                   12670
Split Incident               261
Cumulative Incident           84
Incident,Split Incident        5
Name: count, dtype: int64

In [80]:
df['cause_of_death'].value_counts()

cause_of_death
Drowning                                                                                                                   3313
Mixed or unknown                                                                                                           3175
Vehicle accident / death linked to hazardous transport                                                                     2112
Harsh environmental conditions / lack of adequate shelter, food, water                                                     1360
Violence                                                                                                                   1313
Sickness / lack of access to adequate healthcare                                                                           1219
Accidental death                                                                                                            507
Drowning,Harsh environmental conditions / lack of adequate shelter, food, water                                               8
Drowning,Mixed or unknown                                                                                                     4
Harsh environmental conditions / lack of adequate shelter, food, water,Sickness / lack of access to adequate healthcare       3
Drowning,Violence                                                                                                             2
Drowning,Vehicle accident / death linked to hazardous transport                                                               1
Harsh environmental conditions / lack of adequate shelter, food, water,Mixed or unknown                                       1
Mixed or unknown,Vehicle accident / death linked to hazardous transport,Violence                                              1
Drowning,Sickness / lack of access to adequate healthcare                                                                     1
Name: count, dtype: int64

In [81]:
df['cause_of_death'].value_counts(normalize=True)*100
#The number one leading cause of death (by a small margin) was drowning followed by mixed or unknown cause of death and this was followed by vehicle accident/death linked to hazardous transport.

cause_of_death
Drowning                                                                                                                   25.445469
Mixed or unknown                                                                                                           24.385561
Vehicle accident / death linked to hazardous transport                                                                     16.221198
Harsh environmental conditions / lack of adequate shelter, food, water                                                     10.445469
Violence                                                                                                                   10.084485
Sickness / lack of access to adequate healthcare                                                                            9.362519
Accidental death                                                                                                            3.894009
Drowning,Harsh environmental conditions / lack of adequate shelter, food, water                                             0.061444
Drowning,Mixed or unknown                                                                                                   0.030722
Harsh environmental conditions / lack of adequate shelter, food, water,Sickness / lack of access to adequate healthcare     0.023041
Drowning,Violence                                                                                                           0.015361
Drowning,Vehicle accident / death linked to hazardous transport                                                             0.007680
Harsh environmental conditions / lack of adequate shelter, food, water,Mixed or unknown                                     0.007680
Mixed or unknown,Vehicle accident / death linked to hazardous transport,Violence                                            0.007680
Drowning,Sickness / lack of access to adequate healthcare                                                                   0.007680
Name: proportion, dtype: float64

In [82]:
df.groupby("region_of_incident")['cause_of_death'].value_counts(normalize=True)*100

region_of_incident  cause_of_death
Caribbean           Drowning                                                                  80.000000
                    Mixed or unknown                                                           6.875000
                    Violence                                                                   5.000000
                    Harsh environmental conditions / lack of adequate shelter, food, water     4.375000
                    Vehicle accident / death linked to hazardous transport                     3.125000
                                                                                                ...
Western Asia        Vehicle accident / death linked to hazardous transport                     9.420290
                    Harsh environmental conditions / lack of adequate shelter, food, water     8.937198
                    Mixed or unknown                                                           3.623188
                    Sickness / lack of access to adequate healthcare                           1.449275
                    Accidental death                                                           0.483092
Name: proportion, Length: 113, dtype: float64

In [83]:
df.groupby("region_of_incident")['cause_of_death'].value_counts()
result_df = df.groupby("region_of_incident")['cause_of_death'].value_counts().head(40).to_frame('Count').reset_index()
result_df

,region_of_incident,cause_of_death,Count
0,Caribbean,Drowning,128
1,Caribbean,Mixed or unknown,11
2,Caribbean,Violence,8
3,Caribbean,Harsh environmental conditions / lack of adequ...,7
4,Caribbean,Vehicle accident / death linked to hazardous t...,5
5,Caribbean,Accidental death,1
6,Central America,Drowning,591
7,Central America,Vehicle accident / death linked to hazardous t...,339
8,Central America,Violence,151
9,Central America,Mixed or unknown,132
10,Central America,Sickness / lack of access to adequate healthcare,75
11,Central America,Harsh environmental conditions / lack of adequ...,62
12,Central America,Accidental death,23
13,Central America,"Drowning,Sickness / lack of access to adequate...",1
14,Central America,"Drowning,Violence",1
15,Central Asia,Vehicle accident / death linked to hazardous t...,1
16,Eastern Africa,Mixed or unknown,112
17,Eastern Africa,Violence,105
18,Eastern Africa,Sickness / lack of access to adequate healthcare,94
19,Eastern Africa,Vehicle accident / death linked to hazardous t...,61
20,Eastern Africa,Drowning,56
21,Eastern Africa,Harsh environmental conditions / lack of adequ...,56
22,Eastern Africa,Accidental death,5
23,Eastern Asia,Drowning,6
24,Eastern Asia,Accidental death,1
25,Eastern Asia,Mixed or unknown,1
26,Eastern Asia,Vehicle accident / death linked to hazardous t...,1
27,Eastern Asia,Violence,1
28,Europe,Vehicle accident / death linked to hazardous t...,255
29,Europe,Drowning,125
30,Europe,Harsh environmental conditions / lack of adequ...,71
31,Europe,Mixed or unknown,59
32,Europe,Violence,56
33,Europe,Sickness / lack of access to adequate healthcare,28
34,Europe,Accidental death,25
35,Mediterranean,Drowning,1699
36,Mediterranean,Mixed or unknown,197
37,Mediterranean,Harsh environmental conditions / lack of adequ...,55
38,Mediterranean,Vehicle accident / death linked to hazardous t...,38
39,Mediterranean,Sickness / lack of access to adequate healthcare,24

In [84]:
df[['number_of_dead', 'number_of_females', 'number_of_males', 'number_of_children']] = df[['number_of_dead', 'number_of_females', 'number_of_males', 'number_of_children']].apply(pd.to_numeric, errors='coerce')
df.groupby("incident_year")[[
    'number_of_dead',
    'number_of_females',
    'number_of_males',
    'number_of_children'
]].sum()
#Number of dead and number of identified persons don't match, so not able to pull much about the persons per year.

,number_of_dead,number_of_females,number_of_males,number_of_children
incident_year,,,,
2014,1753.0,67,263,302
2015,4094.0,232,821,305
2016,4294.0,375,997,281
2017,3726.0,547,1606,315
2018,3203.0,1975,1771,363
2019,3622.0,887,1810,537
2020,2354.0,341,1585,159
2021,3651.0,719,2438,336
2022,4296.0,659,2623,369
2023,1725.0,166,617,133

In [85]:
df[['number_of_dead', 'number_of_females', 'number_of_males', 'number_of_children','number_of_survivors']] = df[['number_of_dead', 'number_of_females', 'number_of_males', 'number_of_children','number_of_survivors']].apply(pd.to_numeric, errors='coerce')
df.groupby("region_of_incident")[[
    'number_of_dead',
    'number_of_females',
    'number_of_males',
    'number_of_children',
    'number_of_survivors'
]].sum().sort_values(by='number_of_dead', ascending=False).head(45)

,number_of_dead,number_of_females,number_of_males,number_of_children,number_of_survivors
region_of_incident,,,,,
Mediterranean,9703.0,2600,3807,1104,57411
Northern Africa,5702.0,974,1669,410,6793
North America,3707.0,331,1983,64,934
Southern Asia,2272.0,172,1497,201,1076
Western Africa,2180.0,443,951,251,2360
Central America,2049.0,288,1310,179,3091
Western Asia,1931.0,327,1166,136,4163
Eastern Africa,1624.0,107,445,90,1658
South-eastern Asia,1321.0,325,314,440,4641
Europe,962.0,79,662,98,1476
Caribbean,454.0,218,367,45,1179
South America,420.0,83,200,55,369
Middle Africa,207.0,16,86,24,74
Southern Africa,113.0,4,65,3,64
Central Asia,52.0,0,0,0,5
Eastern Asia,21.0,1,9,0,36

In [86]:
df.groupby("incident_year")['cause_of_death'].value_counts().head(40)
result_df = df.groupby("incident_year")['cause_of_death'].value_counts().head(40).to_frame('Count').reset_index()
result_df

    incident_year                                     cause_of_death  Count
0            2014                                   Mixed or unknown    138
1            2014                                           Drowning     83
2            2014  Vehicle accident / death linked to hazardous t...     25
3            2014  Harsh environmental conditions / lack of adequ...     23
4            2014                                           Violence     22
5            2014                                   Accidental death      3
6            2014                          Drowning,Mixed or unknown      1
7            2014   Sickness / lack of access to adequate healthcare      1
8            2015                                           Drowning    238
9            2015                                   Mixed or unknown    234
10           2015  Vehicle accident / death linked to hazardous t...    118
11           2015  Harsh environmental conditions / lack of adequ...     92
12           2015                                           Violence     83
13           2015   Sickness / lack of access to adequate healthcare     47
14           2015                                   Accidental death      8
15           2015                          Drowning,Mixed or unknown      1
16           2016                                   Mixed or unknown    428
17           2016                                           Drowning    236
18           2016  Vehicle accident / death linked to hazardous t...    191
19           2016                                           Violence    183
20           2016  Harsh environmental conditions / lack of adequ...    126
21           2016   Sickness / lack of access to adequate healthcare    105
22           2016                                   Accidental death      7
23           2016  Drowning,Harsh environmental conditions / lack...      1
24           2017                                   Mixed or unknown    400
25           2017                                           Drowning    314
26           2017  Vehicle accident / death linked to hazardous t...    252
27           2017  Harsh environmental conditions / lack of adequ...    154
28           2017                                           Violence    137
29           2017   Sickness / lack of access to adequate healthcare     77
30           2017                                   Accidental death      5
31           2017                          Drowning,Mixed or unknown      1
32           2017  Drowning,Vehicle accident / death linked to ha...      1
33           2018                                   Mixed or unknown    493
34           2018                                           Drowning    360
35           2018  Vehicle accident / death linked to hazardous t...    251
36           2018   Sickness / lack of access to adequate healthcare    226
37           2018                                           Violence    159
38           2018  Harsh environmental conditions / lack of adequ...    138
39           2018                                   Accidental death      9

In [87]:
df.groupby("region_of_incident")['migration_route'].value_counts(ascending=False)

region_of_incident  migration_route
Caribbean           Caribbean to US                                            54
                    Dominican Republic to Puerto Rico                          42
                    Unknown                                                    32
                    Haiti to Dominican Republic                                17
                    Venezuela to Caribbean                                     10
                    Western Africa / Atlantic route to the Canary Islands       3
                    Caribbean to Central America                                1
                    US-Mexico border crossing                                   1
Central America     US-Mexico border crossing                                 705
                    Unknown                                                   581
                    Darien                                                     88
                    Western Africa / Atlantic route to the Canary Islands       1
Central Asia        Unknown                                                     1
Eastern Africa      Unknown                                                   390
                    Horn of Africa to Yemen crossing                           63
                    Sahara Desert crossing                                     21
                    Comoros to Mayotte                                         14
                    DRC to Uganda                                               1
Eastern Asia        Unknown                                                    10
Europe              Western Balkans                                           209
                    English Channel to the UK                                 134
                    Unknown                                                   126
                    Belarus-EU border                                          61
                    Türkiye-Europe land route                                  46
                    Italy to France                                            33
                    Ukraine to Europe                                           9
                    Eastern Mediterranean                                       1
Mediterranean       Central Mediterranean                                    1106
                    Western Mediterranean                                     614
                    Eastern Mediterranean                                     335
Middle Africa       Unknown                                                    38
                    Sahara Desert crossing                                     35
                    DRC to Uganda                                               2
North America       US-Mexico border crossing                                2686
                    Unknown                                                    11
                    Caribbean to US                                             9
Northern Africa     Sahara Desert crossing                                   1524
                    Unknown                                                   295
                    Western Africa / Atlantic route to the Canary Islands     192
                    Central Mediterranean,Sahara Desert crossing                1
                    Horn of Africa to Yemen crossing                            1
                    Western Balkans                                             1
South America       Unknown                                                   197
                    Darien                                                     10
                    Venezuela to Caribbean                                      1
                    Western Africa / Atlantic route to the Canary Islands       1
South-eastern Asia  Unknown                                                   237
Southern Africa     Unknown                                                    14
                    Comoros to Mayotte                                          2
Southern Asia       Afghanistan to Iran                                      1099
                    Unknown                                                   560
                    Iran to Türkiye                                            14
Western Africa      Unknown                                                   472
                    Sahara Desert crossing                                    466
                    Western Africa / Atlantic route to the Canary Islands      29
Western Asia        Syria to Türkiye                                          129
                    Türkiye-Europe land route                                 111
                    Horn of Africa to Yemen crossing                           97
                    Unknown                                                    57
                    Iran to Türkiye                                            20
Name: count, dtype: int64

In [88]:
df["migration_route"].value_counts()

migration_route
US-Mexico border crossing                                3392
Unknown                                                  3021
Sahara Desert crossing                                   2046
Central Mediterranean                                    1106
Afghanistan to Iran                                      1099
Western Mediterranean                                     614
Eastern Mediterranean                                     336
Western Africa / Atlantic route to the Canary Islands     226
Western Balkans                                           210
Horn of Africa to Yemen crossing                          161
Türkiye-Europe land route                                 157
English Channel to the UK                                 134
Syria to Türkiye                                          129
Darien                                                     98
Caribbean to US                                            63
Belarus-EU border                                          61
Dominican Republic to Puerto Rico                          42
Iran to Türkiye                                            34
Italy to France                                            33
Haiti to Dominican Republic                                17
Comoros to Mayotte                                         16
Venezuela to Caribbean                                     11
Ukraine to Europe                                           9
DRC to Uganda                                               3
Central Mediterranean,Sahara Desert crossing                1
Caribbean to Central America                                1
Name: count, dtype: int64

In [89]:
df.groupby("migration_route")['number_of_dead'].sum().sort_values(ascending=False)

migration_route
Unknown                                                  7412.0
Central Mediterranean                                    7114.0
Sahara Desert crossing                                   5617.0
US-Mexico border crossing                                4512.0
Eastern Mediterranean                                    1548.0
Horn of Africa to Yemen crossing                         1512.0
Afghanistan to Iran                                      1234.0
Western Mediterranean                                    1042.0
Western Africa / Atlantic route to the Canary Islands     867.0
Western Balkans                                           314.0
Syria to Türkiye                                          262.0
Türkiye-Europe land route                                 238.0
English Channel to the UK                                 204.0
Iran to Türkiye                                           189.0
Darien                                                    171.0
Caribbean to US                                           109.0
Dominican Republic to Puerto Rico                          77.0
Comoros to Mayotte                                         70.0
Belarus-EU border                                          61.0
Haiti to Dominican Republic                                55.0
Venezuela to Caribbean                                     55.0
Italy to France                                            34.0
Ukraine to Europe                                          10.0
DRC to Uganda                                               8.0
Central Mediterranean,Sahara Desert crossing                3.0
Caribbean to Central America                                0.0
Name: number_of_dead, dtype: float64

In [90]:
df.to_csv('cleaned_missing_migrants.csv', index = False)

## SQL Analysis: 
This analysis explores the high risk regions, migration routes, most frequent incidents, and total deaths spanning 2014-2023.

In [91]:
import sqlite3
conn = sqlite3.connect("MissingMigrants.db")

In [92]:
df.to_sql("MissingMigrants", conn, if_exists = "replace", index = False)

13020

### Number of Dead and Missing based on the Region of Incident ###

In [93]:
query = """
SELECT "region_of_incident", SUM("number_of_dead") as deaths, SUM(minimum_estimated_number_of_missing) AS est_missing
FROM MissingMigrants
GROUP BY region_of_incident
ORDER BY deaths DESC;

"""
result = pd.read_sql_query (query, conn)
result

    region_of_incident  deaths  est_missing
0        Mediterranean  9703.0        17972
1      Northern Africa  5702.0         2197
2        North America  3707.0           63
3        Southern Asia  2272.0          222
4       Western Africa  2180.0          585
5      Central America  2049.0          204
6         Western Asia  1931.0          211
7       Eastern Africa  1624.0          313
8   South-eastern Asia  1321.0         1793
9               Europe   962.0           57
10           Caribbean   454.0         1049
11       South America   420.0           47
12       Middle Africa   207.0            7
13     Southern Africa   113.0           48
14        Central Asia    52.0            0
15        Eastern Asia    21.0           27

The top 5 regions of incidents were: Mediterranean (9703), Northern Africa (5702), North America (3707), Southern Asia (2272), and Western Africa (2180).

### Leading Cause Of Death

In [94]:
query = """
SELECT cause_of_death, COUNT("cause_of_death") AS value_count, SUM("number_of_dead") AS deaths, SUM(minimum_estimated_number_of_missing) AS est_missing
FROM MissingMigrants
GROUP BY cause_of_death
ORDER BY value_count DESC;
"""
result = pd.read_sql_query (query, conn)
result

,cause_of_death,value_count,deaths,est_missing
0,Drowning,3313,12578.0,21769
1,Mixed or unknown,3175,6561.0,1965
2,Vehicle accident / death linked to hazardous t...,2112,4887.0,43
3,Harsh environmental conditions / lack of adequ...,1360,2827.0,541
4,Violence,1313,3446.0,141
5,Sickness / lack of access to adequate healthcare,1219,1525.0,48
6,Accidental death,507,697.0,2
7,"Drowning,Harsh environmental conditions / lack...",8,108.0,86
8,"Drowning,Mixed or unknown",4,50.0,181
9,Harsh environmental conditions / lack of adequ...,3,14.0,0
10,"Drowning,Violence",2,3.0,6
11,"Mixed or unknown,Vehicle accident / death link...",1,7.0,0
12,Harsh environmental conditions / lack of adequ...,1,8.0,10
13,"Drowning,Vehicle accident / death linked to ha...",1,3.0,3
14,"Drowning,Sickness / lack of access to adequate...",1,4.0,0

The leading cause of death is drowning followed my mixed or unknown causes of death.

In [98]:
df['cause_of_death'].value_counts()

cause_of_death
Drowning                                                                                                                   3313
Mixed or unknown                                                                                                           3175
Vehicle accident / death linked to hazardous transport                                                                     2112
Harsh environmental conditions / lack of adequate shelter, food, water                                                     1360
Violence                                                                                                                   1313
Sickness / lack of access to adequate healthcare                                                                           1219
Accidental death                                                                                                            507
Drowning,Harsh environmental conditions / lack of adequate shelter, food, water                                               8
Drowning,Mixed or unknown                                                                                                     4
Harsh environmental conditions / lack of adequate shelter, food, water,Sickness / lack of access to adequate healthcare       3
Drowning,Violence                                                                                                             2
Drowning,Vehicle accident / death linked to hazardous transport                                                               1
Harsh environmental conditions / lack of adequate shelter, food, water,Mixed or unknown                                       1
Mixed or unknown,Vehicle accident / death linked to hazardous transport,Violence                                              1
Drowning,Sickness / lack of access to adequate healthcare                                                                     1
Name: count, dtype: int64

In [102]:
query = """
SELECT region_of_incident, cause_of_death, COUNT(*) AS incidents, SUM("number_of_dead") AS deaths, SUM(minimum_estimated_number_of_missing) AS est_missing
FROM MissingMigrants
GROUP BY region_of_incident, cause_of_death
ORDER BY region_of_incident, deaths DESC;
"""
result = pd.read_sql_query (query, conn)
result

,region_of_incident,cause_of_death,incidents,deaths,est_missing
0,Caribbean,Drowning,128,324.0,1002
1,Caribbean,Harsh environmental conditions / lack of adequ...,7,80.0,8
2,Caribbean,Mixed or unknown,11,25.0,39
3,Caribbean,Vehicle accident / death linked to hazardous t...,5,16.0,0
4,Caribbean,Violence,8,8.0,0
...,...,...,...,...,...
108,Western Asia,Vehicle accident / death linked to hazardous t...,39,180.0,0
109,Western Asia,Harsh environmental conditions / lack of adequ...,37,122.0,6
110,Western Asia,Mixed or unknown,15,31.0,21
111,Western Asia,Sickness / lack of access to adequate healthcare,6,12.0,0
112,Western Asia,Accidental death,2,7.0,0

### High Risk Migration Routes

In [101]:
query = """
SELECT
    migration_route,SUM(number_of_dead) AS deaths, SUM(minimum_estimated_number_of_missing) AS est_missing
FROM MissingMigrants
GROUP BY migration_route
ORDER BY deaths DESC;
"""
result = pd.read_sql_query (query, conn)
result

                                      migration_route  deaths  est_missing
0                                             Unknown  7412.0         2521
1                               Central Mediterranean  7114.0        14902
2                              Sahara Desert crossing  5617.0          156
3                           US-Mexico border crossing  4512.0           88
4                               Eastern Mediterranean  1548.0          745
5                    Horn of Africa to Yemen crossing  1512.0          318
6                                 Afghanistan to Iran  1234.0            5
7                               Western Mediterranean  1042.0         2325
8   Western Africa / Atlantic route to the Canary ...   867.0         2571
9                                     Western Balkans   314.0           29
10                                   Syria to Türkiye   262.0           11
11                          Türkiye-Europe land route   238.0           34
12                          English Channel to the UK   204.0            9
13                                    Iran to Türkiye   189.0            6
14                                             Darien   171.0          145
15                                    Caribbean to US   109.0          390
16                  Dominican Republic to Puerto Rico    77.0          228
17                                 Comoros to Mayotte    70.0          144
18                                  Belarus-EU border    61.0            2
19                             Venezuela to Caribbean    55.0          132
20                        Haiti to Dominican Republic    55.0            9
21                                    Italy to France    34.0            0
22                                  Ukraine to Europe    10.0            7
23                                      DRC to Uganda     8.0            1
24       Central Mediterranean,Sahara Desert crossing     3.0            0
25                       Caribbean to Central America     NaN           17

The migration route with the highest deaths are Unknown (7412 deaths) followed by Central Mediterranean (7114), Sahara Desert Crossing (5617 deaths), and US-Mexico Border Crossing (4512 deaths). The number of missing migrants however is more frequently documented in the Central Mediterranean route with 14,902 missing.

In [100]:
query = """
SELECT region_of_incident, migration_route, COUNT(*) AS count, SUM("number_of_dead") AS deaths, SUM(minimum_estimated_number_of_missing) AS est_missing
FROM MissingMigrants
GROUP BY migration_route
ORDER BY region_of_incident, count DESC;
"""
result = pd.read_sql_query (query, conn)
result

,region_of_incident,migration_route,count,deaths,est_missing
0,Caribbean,Caribbean to US,63,109.0,390
1,Caribbean,Dominican Republic to Puerto Rico,42,77.0,228
2,Caribbean,Haiti to Dominican Republic,17,55.0,9
3,Caribbean,Venezuela to Caribbean,11,55.0,132
4,Caribbean,Caribbean to Central America,1,NaN,17
5,Eastern Africa,Horn of Africa to Yemen crossing,161,1512.0,318
6,Eastern Africa,Comoros to Mayotte,16,70.0,144
7,Europe,Unknown,3021,7412.0,2521
8,Europe,Western Balkans,210,314.0,29
9,Europe,English Channel to the UK,134,204.0,9
10,Europe,Belarus-EU border,61,61.0,2
11,Europe,Italy to France,33,34.0,0
12,Europe,Ukraine to Europe,9,10.0,7
13,Mediterranean,Central Mediterranean,1106,7114.0,14902
14,Mediterranean,Western Mediterranean,614,1042.0,2325
15,Mediterranean,Eastern Mediterranean,336,1548.0,745
16,Middle Africa,DRC to Uganda,3,8.0,1
17,North America,US-Mexico border crossing,3392,4512.0,88
18,Northern Africa,Sahara Desert crossing,2046,5617.0,156
19,Northern Africa,Western Africa / Atlantic route to the Canary ...,226,867.0,2571
20,Northern Africa,"Central Mediterranean,Sahara Desert crossing",1,3.0,0
21,South America,Darien,98,171.0,145
22,Southern Asia,Afghanistan to Iran,1099,1234.0,5
23,Western Asia,Türkiye-Europe land route,157,238.0,34
24,Western Asia,Syria to Türkiye,129,262.0,11
25,Western Asia,Iran to Türkiye,34,189.0,6

### Fatalities over Time

In [99]:
query = """
SELECT incident_year, SUM("number_of_dead") AS deaths, SUM(minimum_estimated_number_of_missing) AS est_missing
FROM MissingMigrants
GROUP BY incident_year
ORDER BY incident_year
"""
result = pd.read_sql_query (query, conn)
result

   incident_year  deaths  est_missing
0           2014  1753.0         3568
1           2015  4094.0         2655
2           2016  4294.0         3784
3           2017  3726.0         2564
4           2018  3203.0         1806
5           2019  3622.0         1796
6           2020  2354.0         1947
7           2021  3651.0         2500
8           2022  4296.0         2766
9           2023  1725.0         1409

Deaths and number of missing fluctuates througout the years with minimum at 1725 deaths and 1409 missing and maximums at 4296 deaths and 2766 missing.

Findings:
* The top 5 regions of incidents were: Mediterranean (9703), Northern Africa (5702), North America (3707), Southern Asia (2272), and Western Africa (2180).
* The main leading cause of death is drowning (12578) followed by unknown cause of death (6561) and Vehicle accident / death linked to hazardous transport (4887).
* The migration route with the highest deaths are Unknown (7412 deaths) followed by Central Mediterranean (7114), Sahara Desert Crossing (5617 deaths), and US-Mexico Border Crossing (4512 deaths). The number of missing migrants however is more frequently documented in the Central Mediterranean route with 14,902 missing.
* Deaths and number of missing fluctuates througout the years with the minimums recorded at 1725 deaths and 1409 missing and maximums recorded at 4296 deaths and 2766 missing.

Conclusion:
Across occupations, average sleep quality, stress scores, and work hours varied considerably. Occupations with higher average sleep quality generally reported lower average stress scores, with a moderate negative correlation observed between sleep quality and stress (r = -0.64). Analysis of wake episodes among lawyers showed that increased wake episodes were associated with lower sleep quality and slightly higher stress levels. Overall, the results suggest that sleep quality may be more closely associated with stress than work hours alone within this dataset. However, these findings represent associations rather than causal relationships, and other occupation-specific or individual factors may also contribute to differences in stress levels.